// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(10)
            {
                { typeof(global::Motk.Combat.Shared.Messages.Dto.CombatTeamDto[]), 0 },
                { typeof(global::Motk.Combat.Shared.Messages.Dto.CombatUnitDto[]), 1 },
                { typeof(global::Motk.Combat.Shared.Messages.Dto.CombatUnitIdentifierDto[]), 2 },
                { typeof(global::Motk.HexGrid.Core.HexDirection), 3 },
                { typeof(global::Motk.Combat.Shared.Messages.Dto.CombatTeamDto), 4 },
                { typeof(global::Motk.Combat.Shared.Messages.Dto.CombatUnitDto), 5 },
                { typeof(global::Motk.Combat.Shared.Messages.Dto.CombatUnitIdentifierDto), 6 },
                { typeof(global::Motk.Combat.Shared.Messages.Dto.HexCoordinatesDto), 7 },
                { typeof(global::Motk.Combat.Shared.Messages.Server.CombatStartedMessage), 8 },
                { typeof(global::Motk.Combat.Shared.Messages.Server.NewRoundMessage), 9 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.ArrayFormatter<global::Motk.Combat.Shared.Messages.Dto.CombatTeamDto>();
                case 1: return new global::MessagePack.Formatters.ArrayFormatter<global::Motk.Combat.Shared.Messages.Dto.CombatUnitDto>();
                case 2: return new global::MessagePack.Formatters.ArrayFormatter<global::Motk.Combat.Shared.Messages.Dto.CombatUnitIdentifierDto>();
                case 3: return new MessagePack.Formatters.Motk.HexGrid.Core.HexDirectionFormatter();
                case 4: return new MessagePack.Formatters.Motk.Combat.Shared.Messages.Dto.CombatTeamDtoFormatter();
                case 5: return new MessagePack.Formatters.Motk.Combat.Shared.Messages.Dto.CombatUnitDtoFormatter();
                case 6: return new MessagePack.Formatters.Motk.Combat.Shared.Messages.Dto.CombatUnitIdentifierDtoFormatter();
                case 7: return new MessagePack.Formatters.Motk.Combat.Shared.Messages.Dto.HexCoordinatesDtoFormatter();
                case 8: return new MessagePack.Formatters.Motk.Combat.Shared.Messages.Server.CombatStartedMessageFormatter();
                case 9: return new MessagePack.Formatters.Motk.Combat.Shared.Messages.Server.NewRoundMessageFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name
