// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Motk.Combat.Shared.Messages.Server
{
    public sealed class NewRoundMessageFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Motk.Combat.Shared.Messages.Server.NewRoundMessage>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Motk.Combat.Shared.Messages.Server.NewRoundMessage value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(2);
            writer.Write(value.RoundIndex);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Motk.Combat.Shared.Messages.Dto.CombatUnitIdentifierDto[]>(formatterResolver).Serialize(ref writer, value.TurnsQueue, options);
        }

        public global::Motk.Combat.Shared.Messages.Server.NewRoundMessage Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __RoundIndex__ = default(ushort);
            var __TurnsQueue__ = default(global::Motk.Combat.Shared.Messages.Dto.CombatUnitIdentifierDto[]);

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        __RoundIndex__ = reader.ReadUInt16();
                        break;
                    case 1:
                        __TurnsQueue__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Motk.Combat.Shared.Messages.Dto.CombatUnitIdentifierDto[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Motk.Combat.Shared.Messages.Server.NewRoundMessage(__RoundIndex__, __TurnsQueue__);
            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
